version: "3.3"
services:
    
    postgres:
        image: postgis/postgis:15-3.3-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=ccem
            - POSTGRES_PASSWORD=!ccem23
            - POSTGRES_DB=ccem
        volumes: 
            - database-data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment: 
            - PGADMIN_DEFAULT_EMAIL=ccem@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=!ccem23
        ports:
            - '1000:80'
        volumes: 
            - pgadmin:/root/.pgadmin

    spring: 
        build: ./ccem
        container_name: spring
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ccem
            - SPRING_DATASOURCE_USERNAME=ccem
            - SPRING_DATASOURCE_PASSWORD=!ccem23
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_JPA_DATABASE=POSTGRESQL
            - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
            - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
            - SPRING_JPA_HIBERNATE_DDL_AUTO=none
            - SPRING_JPA_HIBERNATE_SHOW_SQL=true

volumes:
    database-data:
    pgadmin: