//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "regions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub region_id: i32,
    pub space_id: Option<i32>,
    pub name: Option<String>,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::counties::Entity")]
    Counties,
    #[sea_orm(
        belongs_to = "super::spaces::Entity",
        from = "Column::SpaceId",
        to = "super::spaces::Column::SpaceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Spaces,
}

impl Related<super::counties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Counties.def()
    }
}

impl Related<super::spaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
